### ISSUE TITLE
Unlock screen after standby

### ISSUE THREAD

**Issue by Aquan1412** [tiktaalik-dev/blueproximity#14]
Is there a way to use blueproximity to unlock my screen after the computer wakes from standby? It seems that the unlock isn't working if my phone is already present when the computer wakes from standby. However,  if I briefly leave and return with my phone, then the screen gets unlocked.

So it seems as if the program is still working, however, for some reason the unlock command isn't issued when the phone is first detected.

**Comment by tiktaalik-dev** [comment]
Hi @Aquan1412 ,

Sorry for the very late reply!
I reckon what you're experiencing is related with the sequence of steps your system follows when coming back up from standby. For instance, on my laptop I have to deactivate my Bluetooth device before entering suspension state because otherwise the device doesn't wake up afterwards. It seems to be related with the firmware or the driver not triggering a reset instruction after coming back online. Maybe it's something like that for your device too?
On the other hand, as you noticed that if you walk away then it would unlock the screen correctly, I reckon that there may be some terminal command that you could trigger as part of the "Proximity command" sequence that's preconfigured on the application settings ("Locking" tab). I'm not an expert in bash commands so I'm not the best person to advice on that subject, but I can advice that in there you can write any command that you want! It's an editable field that executes whatever bash command you write in there, so maybe you could use a command that checks on the standby state?
Anyway, if I happen to find such command I'll let you know. If you do find it, please let me know as well and I could add it to the sequence for a new version of the software. Deal? :smile:

Cheers,
Rigo
