### ISSUE TITLE
BlueProximity not do any thing (fails) to lock or unlock and all author thing work perfect pls i need some help ???

### ISSUE THREAD

**Issue by AHmedM0stafa** [tiktaalik-dev/blueproximity#18]
![Screenshot from 2022-04-29 11-46-51](https://user-images.githubusercontent.com/103394239/165922194-f1f056ba-33be-499c-81b9-2df0caa579fe.png)

I'm using kali last -v (2022.1) with gnome desktop environment

**Comment by tiktaalik-dev** [comment]
Hi @AHmedM0stafa,

I reckon you have set values that are too tight. The scale for the distance **is not meters or feet** and you set the time at 1 second for both locking and unlocking, so your actual configuration makes the program to keep jumping between states.
Try different settings. Here I'm attaching a screenshot of my actual configuration that works perfectly well, locking the screen when I walk away 4 or 5 meters
![Recommended settings](https://user-images.githubusercontent.com/5922428/166071628-81530281-6267-4a40-8ea8-1d3ec1cbbe26.png)

Cheers,
Rigo

P.S.: Gnome is known to be problematic for BlueProximity because Gnome removed compatibility with status icons. Check the other issues reported about it.

**Comment by tiktaalik-dev** [comment]
I'm closing this issue as it has no new activity after my reply. In case you have something else to report, please feel free to reopen it. Cheers.
