### ISSUE TITLE
Cannot install due to missing directory

### ISSUE THREAD

**Issue by CRPrinzler** [tiktaalik-dev/blueproximity#3]
`pip3 install -t requirements.txt
ERROR: Target path exists but is not a directory, will not continue.
`
Any ideas?

**Comment by tiktaalik-dev** [comment]
Hi CRPrinzler,

Thanks for letting me know about this! It was my mistake. Sorry about that. I had typed the wrong parameter for that command (-t instead of -r). I've upgraded the README file with the right instruction and also added another command that you should run before pip. Please check the new instructions up!
I also fixed the name of the packages in the file requirements.txt as pip uses a different name than what I thought it does, so please download the updated file before running pip3 again.
On a side note, if you just intend to run it in your system (instead of developing) maybe you could just try to execute the start_proximity.sh file. Probably every linux distro has python already installed, so you probably will find it runs just fine without creating a virtual environment.

Let me know how it goes, please.

Cheers,
Rigo.

**Comment by CRPrinzler** [comment]
Thx for your quick reply. I will try this at once.
