### ISSUE TITLE
Will it work when the phone screen locks

### ISSUE THREAD

**Issue by prasadpnair** [tiktaalik-dev/blueproximity#5]
The original blueproximity was not working when the phone screen is locked (OnePlus 5 and Linux Mint 19.3 ). When the phone screen locks, it's not able to determine the distance which locks the computer also. So I was not able to use it b'cos when I was working all of sudden the laptop gets locked. Is this fixed in this new version? Also any plans for supporting BLE devices like MiBand. It'll be a great value addition. I'm sure there are lot of takers for this.

Last question? How to install this in Linux Mint 20? Should I just copy the scripts and run?

**Comment by prasadpnair** [comment]
When I run, I'm getting the following error
The program cannot import the module gobject.
Please make sure the GObject bindings for python are installed.
e.g. with Ubuntu Linux, type
 sudo apt-get install python3-gobject

I have python3-gi installed

**Comment by tiktaalik-dev** [comment]
Hi prasadpnair,

Thanks for reaching out :-)

In my experience when the screen gets suddenly locked, even if your phone is right there on your desk, it usually is because of phone settings. Many phones turn off Bluetooth. It may be due to battery saving apps, like Avast Battery Saver, where you can configure several profiles and if your battery drops below 25% then the Emergency profile kicks in and the default configuration for that profile turns Bluetooth off. So, I'd start by checking that up.
On the other hand, if Bluetooth isn't being turned off in your phone settings, your problem may be due to the Bluetooth channel. Maybe it's being used by some other process as well or somehow there's any interference? When that happens to me, I simply open Blueproximity's main window and click on "Scan channels", then just choose any other channel that shows up as open.
A final option might be to fine tune your settings on the "Proximity details" tab. Try different values for distance and specially for "Duration". Bear in mind that those values are NOT exactly meters (or feet)! For instance, I've found that the following settings are the best for me:

- Locking distance: 13
- Locking duration: 15
- Unlocking distance: 8
- Unlocking duration: 5

Take advantage of the last slider, "Measured atm", where you can see in real-time what distance does Blueproximity is detecting for your phone. As long as you have the application window open, your screen won't be locked so you can confidently play with different values until you find what works best for you. But if you see that the distance detected at the moment is greater than 0 even if your phone is next to your laptop, try changing to a different channel first. Also remember that if your phone is in your pocket then your body will become a physical barrier for the Bluetooth signal, so Blueproximity will "think" that your phone is far away ;-)
As for your question about installing it in Linux Mint 20, that's my current distro too! So I can guarantee that it does work. I haven't had time yet to learn how to build a .deb package though, sorry about that. But if you just copy this app in a folder somewhere in your home directory then execute the _start_proximity.sh_ script to start the program up (remember to make the script executable!). If you get error messages about missing dependencies install them and try again. Once you get it working from the terminal then just create a shortcut in your desktop and that's it.

Hope that helps.

Cheers,
Rigo

P.S.: About you BLE device, I don't own any such device so I don't even know if those work or not. Sorry about that. Maybe someone else can chime in?
