### ISSUE TITLE
Kind: bug. Cannot create new configuration.

### ISSUE THREAD

**Issue by AlexGluck** [tiktaalik-dev/blueproximity#8]
```
Traceback (most recent call last):
  File "/home/alexgluck/files/git_repos/private/blueproximity/proximity.py", line 434, in dlgNewDo_clicked
    newconfig = self.wTree.get_widget("entryNewName").get_text()
AttributeError: 'Builder' object has no attribute 'get_widget'
```
OS: Fedora 33 Workstation, python 3.9.1

Step to reproduce:
1. Run `/usr/bin/python3.9 proximity.py`
2. Press "Create" button
3. Write "asdasdasd"
4. Press "Create" button in dialog form

Installation and requirements for fedora 33:
```
sudo dnf install -y bluez-libs-devel python3-gobject python3-gobject-base xapps python3-xapp python3-bluez python3-configobj
git clone $BLUEPROXIMITY_REPO folder ; cd folder ; /usr/bin/python3 proximity.py
```

**Comment by tiktaalik-dev** [comment]
Hi @AlexGluck,

Sorry for the very late reply! As I commented on the other issue you raised, some how I missed the notification. I'm really sorry about it :-(
from what I see in your report, it probably happened because you executed the `proximity.py` file directly. You need to execute the shell file `start_proximity.sh` instead. Even better, please try the AppImage package I included along with the last release. You can find it here: [https://github.com/tiktaalik-dev/blueproximity/releases/tag/v1.3.3](https://github.com/tiktaalik-dev/blueproximity/releases/tag/v1.3.3)

Cheers,
Rodrigo Gambra
[Tiktaalik Dev](https://tiktaalik.dev)

**Comment by tiktaalik-dev** [comment]
I'm closing this issue as it has no new activity after my reply. In case you have something else to report, please feel free to reopen it. Cheers.
