### ISSUE TITLE
Kind: bug. Proximity.py broken cursor

### ISSUE THREAD

**Issue by AlexGluck** [tiktaalik-dev/blueproximity#9]
OS: Fedora 33 Workstation, python 3.9.1

Step to reproduce:
1. Run `/usr/bin/python3.9 proximity.py`

![photo_2021-01-31_22-50-11](https://user-images.githubusercontent.com/8583390/106396052-b396e180-6416-11eb-879a-63ee4e326379.jpg)

**Comment by soorajsprakash** [comment]
same for me,
using Gnome in Arch

**Comment by tiktaalik-dev** [comment]
Hi guys,

Sorry for the very late reply! Somehow I missed the notification for your issue :-(
Your problem is likely related to Gnome. Since Gnome decided to eliminate the Status icons from their desktop without providing an alternative, it causes all kind of malfunctions.
Though as it may also be related to some missing dependencies, please try the AppImage package I provided along with the last release and let me know how it went for you. It includes all the dependencies in a self-contained executable file. You can find it here: [https://github.com/tiktaalik-dev/blueproximity/releases/tag/v1.3.3](https://github.com/tiktaalik-dev/blueproximity/releases/tag/v1.3.3)

Cheers,
Rodrigo Gambra
[Tiktaalik Dev](https://tiktaalik.dev)

**Comment by tiktaalik-dev** [comment]
I'm closing this issue as it has no new activity after my reply. In case you have something else to report, please feel free to reopen it. Cheers.
